In [20]:
%load_ext autoreload
%autoreload 2

In [134]:
import sys
import os
import torch
from torch.utils.data import Dataset, DataLoader

import torch.nn as nn

from generate_data import RandomIntegerDataset

In [96]:
sys.path.append(os.path.abspath(".."))
from embedding import CustomEmbedding
sys.path.remove(os.path.abspath(".."))

In [99]:
N_WORDS = 10

embeddings = CustomEmbedding(N_WORDS + 3, 8) # 3 = PAD, SOS, EOS

indices = torch.tensor([1,9], dtype = torch.int64)

print(embeddings.embeddings.weight)
print(embeddings.embeddings(indices))

Parameter containing:
tensor([[-0.5883, -0.4169,  0.5113,  0.0620,  1.9436,  0.5713, -0.5328, -0.4432],
        [-0.2558, -1.0582, -0.9108, -0.9217,  0.3481, -0.4505,  1.6085,  1.0954],
        [ 0.5305,  0.1746,  0.7818, -0.9394,  1.9737, -0.0071,  0.7987, -1.0126],
        [ 0.2547, -0.8258,  0.3831,  1.2844,  1.0588,  1.7994, -0.0411, -0.3108],
        [ 0.5195, -1.7401, -1.0367, -0.6395, -1.2437,  1.2663,  0.0127, -0.8008],
        [ 1.3834,  0.6505, -0.1878,  0.3797, -0.6840,  1.4687, -2.6809, -0.3775],
        [ 0.4305,  1.2888, -1.7802, -0.0608, -0.0814,  0.3278,  1.2174,  0.1904],
        [-0.7199,  0.3571,  0.0219,  0.4970, -1.1759, -1.4723, -0.1233,  0.9309],
        [-0.1171, -0.9301,  0.6343,  0.4795, -0.9458, -1.5227, -1.3528,  1.2140],
        [-0.7659,  1.9569,  0.3681, -1.6962,  0.2449,  0.2973,  0.8388,  1.9350],
        [-1.3392, -0.3317, -0.5830,  0.6540, -0.2970,  0.1539,  1.5088, -0.8474],
        [-0.8325,  0.0559,  0.8497, -0.8626,  0.9420, -0.7838,  0.6400, -0.6

In [ ]:
BATCH_SIZE = 2

rand_ds = RandomIntegerDataset(2, 10, 10, [i for i in range(10)])
dataloader = DataLoader(rand_ds, batch_size = BATCH_SIZE, shuffle = True)

In [133]:
input, label = next(iter(dataloader))
print(input[0])
print(input[1])
print(label)

tensor([[ 1,  9,  0, 11, 11, 11, 11, 11, 11, 11],
        [ 7,  5,  3,  9,  6,  2, 11, 11, 11, 11]])
tensor([[12,  0,  1,  9, 11, 11, 11, 11, 11, 11, 11],
        [12,  2,  3,  5,  6,  7,  9, 11, 11, 11, 11]])
tensor([[ 0,  1,  9, 13, 11, 11, 11, 11, 11, 11, 11],
        [ 2,  3,  5,  6,  7,  9, 13, 11, 11, 11, 11]])


In [ ]:
LEARNING_RATE = 1e-3

loss_fn = nn.CrossEntropyLoss()
optim = torch.optim.SGD(params = ..., lr = LEARNING_RATE, momentum = 0.9, weight_decay = 1e-4)

In [ ]:
def run_train_epoch(dataloader: DataLoader, model, loss_fn, optimizer):
    pass

def run_test_loop(dataloader: DataLoader, model, loss_fn):
    pass