In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
import os
import torch
from torch.utils.data import Dataset, DataLoader

import torch.nn as nn
from embedding import CustomEmbedding
from transformers import Transformer

from generate_data import RandomIntegerDataset

In [5]:
N_WORDS = 10
vocab_size = N_WORDS + 3
D_MODEL = 16

embeddings = CustomEmbedding(vocab_size = vocab_size, d_model = D_MODEL) # 3 = PAD, SOS, EOS

# indices = torch.tensor([1,9])

# print(embeddings.embeddings.weight)
# print(embeddings.embeddings(indices))

In [23]:
BATCH_SIZE = 2

rand_ds = RandomIntegerDataset(2, 10, 10, [i for i in range(10)])
dataloader = DataLoader(rand_ds, batch_size = BATCH_SIZE, shuffle = True)

torch.Size([10, 10])
torch.Size([10, 11])
torch.Size([10, 11])


In [25]:
input, label = next(iter(dataloader))
print(input[0])
print(input[1])
print(label)

tensor([[ 4,  8,  2,  9,  0,  7,  6,  3,  1,  5],
        [ 0,  2,  7, 10, 10, 10, 10, 10, 10, 10]])
tensor([[11,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [11,  0,  2,  7, 10, 10, 10, 10, 10, 10, 10]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 12],
        [ 0,  2,  7, 12, 10, 10, 10, 10, 10, 10, 10]])


In [26]:
loss_fn = nn.CrossEntropyLoss()

model = Transformer(embeddings = embeddings, 
                    vocab_size = vocab_size, 
                    d_model = D_MODEL, 
                    num_attention_heads = 4, 
                    num_encoder_layers = 6, 
                    num_decoder_layers = 6, 
                    dim_feedforward = 64, 
                    max_context_window = 50)

optim = torch.optim.SGD(params = model.parameters(), lr = 1e-3, momentum = 0.9, weight_decay = 1e-4)

In [29]:
# def run_train_epoch(dataloader: DataLoader, model: nn.Module, loss_fn: nn.Module, optimizer: torch.optim.Optimizer):
    
#     model.train()

#     for i, ((source, target), label) in enumerate(dataloader):

#         print(source)
#         print(target)

#         # FORWARD
#         pred = model(source, target)

#         batch_loss = loss_fn(pred, label)

#         # BACKWARD
#         batch_loss.backward()

#         # OPTIMIZE
#         optimizer.step()
#         optimizer.zero_grad()

# def run_test_loop(dataloader: DataLoader, model: nn.Module, loss_fn: nn.Module):
    
#     model.eval()

In [30]:
# EPOCHS = 1

# for i in range(EPOCHS):

#     run_train_epoch(dataloader, model, loss_fn, optim)